version: '3'
services:
  web:
    restart: always
    image: avral/dtrip
    build:
      context: .
      args:                                                                      
        PROD: ${PROD}
        API_QL_URL: ${API_QL_URL}
        BASE_URL: ${BASE_URL}
        SENTRY_DSN: ${SENTRY_DSN}
    command: yarn run start
    ports:
      - 127.0.0.1:1000:3000

  spa-build:
    volumes:
      - "./dist/:/app/_dist"
    image: avral/dtrip
    command: sh -c "yarn run build --spa && mv -v dist/* _dist"

#networks:
#  default:
#    external:
#      name: dtrip-api_default
